channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3
  - pyqt
  - pyqtgraph
  - h5py
  - scipy
  - numpy
  - tqdm
  - pyopencl
  - pip
  - ipython
  - configparser
  - prody
  - pyopengl
